### PR TITLE
Fixes #2 - Add read permissions to LICENCE.txt

### LINKED ISSUE #2: Galaxy's mulled-build fails due to file permissions of the licence
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Hello,

At Bioconda project we experience a build failure for every recipe that depends transitively on font-ttf-ubuntu - https://github.com/bioconda/bioconda-recipes/pull/46177#issuecomment-2079659198

The problem is that the file permissions of the files inside `pkg-font-ttf-ubuntu-0.83-h77eed37_1.tar.zst ` have `600` permissions, i.e. only the owner user can read and write, but group and others cannot even read it.

Galaxy's mulled-build tries to copy the LICENCE.txt file and fails with `Permission denied`.

Is there a way to modify the permissions to `644` for example and publish a new build of this feedstock ?

### Installed packages

```shell
Package                                           Version  Build                     Channel                        Size
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  [32m+ _openmp_mutex                            [0m           4.5  2_gnu                     conda-forge/linux-aarch64      24kB
  [32m+ _r-mutex                                 [0m         1.0.1  anacondar_1               conda-forge/noarch              4kB
  [32m+ _sysroot_linux-aarch64_curr_repodata_hack[0m             4  h57d6b7b_14               conda-forge/noarch             21kB
  [32m+ binutils_impl_linux-aarch64              [0m          2.40  hd42cb95_0                conda-forge/linux-aarch64       7MB
  [32m+ bwidget                                  [0m        1.9.14  h8af1aa0_1                conda-forge/linux-aarch64     122kB
  [32m+ bzip2                                    [0m         1.0.8  h31becfc_5                conda-forge/linux-aarch64     190kB
  [32m+ c-ares                                   [0m        1.28.1  h31becfc_0                conda-forge/linux-aarch64     176kB
  [32m+ ca-certificates                          [0m      2024.2.2  hcefe29a_0                conda-forge/linux-aarch64     156kB
  [32m+ cairo                                    [0m        1.18.0  ha13f110_0                conda-forge/linux-aarch64     984kB
  [32m+ curl                                     [0m         8.7.1  h4e8248e_0                conda-forge/linux-aarch64     168kB
  [32m+ expat                                    [0m         2.6.2  h2f0025b_0                conda-forge/linux-aarch64     128kB
  [32m+ font-ttf-dejavu-sans-mono                [0m          2.37  hab24e00_0                conda-forge/noarch            397kB
  [32m+ font-ttf-inconsolata                     [0m         3.000  h77eed37_0                conda-forge/noarch             97kB
  [32m+ font-ttf-source-code-pro                 [0m         2.038  h77eed37_0                conda-forge/noarch            701kB
  [32m+ font-ttf-ubuntu                          [0m          0.83  h77eed37_1                conda-forge/noarch              2MB
  [32m+ fontconfig                               [0m        2.14.2  ha9a116f_0                conda-forge/linux-aarch64     280kB
  [32m+ fonts-conda-ecosystem                    [0m             1  0                         conda-forge/noarch              4kB
  [32m+ fonts-conda-forge                        [0m             1  0                         conda-forge/noarch              4kB
  [32m+ freetype                                 [0m        2.12.1  hf0a5ef3_2                conda-forge/linux-aarch64     642kB
  [32m+ fribidi                                  [0m        1.0.10  hb9de7d4_0                conda-forge/linux-aarch64     116kB
  [32m+ gcc_impl_linux-aarch64                   [0m        13.2.0  h5669b93_5                conda-forge/linux-aarch64      49MB
  [32m+ gettext                                  [0m        0.22.5  h2f0025b_2                conda-forge/linux-aarch64     476kB
  [32m+ gettext-tools                            [0m        0.22.5  h2f0025b_2                conda-forge/linux-aarch64       3MB
  [32m+ gfortran_impl_linux-aarch64              [0m        13.2.0  h2e87c2d_5                conda-forge/linux-aarch64      13MB
  [32m+ graphite2                                [0m        1.3.13  h2f0025b_1003             conda-forge/linux-aarch64      99kB
  [32m+ gxx_impl_linux-aarch64                   [0m        13.2.0  h5669b93_5                conda-forge/linux-aarch64      12MB
  [32m+ harfbuzz                                 [0m         8.3.0  hebeb849_0                conda-forge/linux-aarch64       2MB
  [32m+ icu                                      [0m          73.2  h787c7f5_0                conda-forge/linux-aarch64      12MB
  [32m+ kernel-headers_linux-aarch64             [0m        4.18.0  h5b4a56d_14               conda-forge/noarch              1MB
  [32m+ keyutils                                 [0m         1.6.1  h4e544f5_0                conda-forge/linux-aarch64     112kB
  [32m+ krb5                                     [0m        1.21.2  hc419048_0                conda-forge/linux-aarch64       1MB
  [32m+ ld_impl_linux-aarch64                    [0m          2.40  hba4e955_0                conda-forge/linux-aarch64     735kB
  [32m+ lerc                                     [0m         4.0.0  h4de3ea5_0                conda-forge/linux-aarch64     262kB
  [32m+ libasprintf                              [0m        0.22.5  h7b6a552_2                conda-forge/linux-aarch64      43kB
  [32m+ libasprintf-devel                        [0m        0.22.5  h7b6a552_2                conda-forge/linux-aarch64      34kB
  [32m+ libblas                                  [0m         3.9.0  22_linuxaarch64_openblas  conda-forge/linux-aarch64      15kB
  [32m+ libcurl                                  [0m         8.7.1  h4e8248e_0                conda-forge/linux-aarch64     410kB
  [32m+ libdeflate                               [0m          1.20  h31becfc_0                conda-forge/linux-aarch64      70kB
  [32m+ libedit                                  [0m  3.1.20191231  he28a2e2_2                conda-forge/linux-aarch64     134kB
  [32m+ libev                                    [0m          4.33  h31becfc_2                conda-forge/linux-aarch64     115kB
  [32m+ libexpat                                 [0m         2.6.2  h2f0025b_0                conda-forge/linux-aarch64      73kB
  [32m+ libffi                                   [0m         3.4.2  h3557bc0_5                conda-forge/linux-aarch64      59kB
  [32m+ libgcc-devel_linux-aarch64               [0m        13.2.0  h0a96a4f_105              conda-forge/noarch              2MB
  [32m+ libgcc-ng                                [0m        13.2.0  hf8544c7_5                conda-forge/linux-aarch64     457kB
  [32m+ libgettextpo                             [0m        0.22.5  h2f0025b_2                conda-forge/linux-aarch64     200kB
  [32m+ libgettextpo-devel                       [0m        0.22.5  h2f0025b_2                conda-forge/linux-aarch64      37kB
  [32m+ libgfortran-ng                           [0m        13.2.0  he9431aa_5                conda-forge/linux-aarch64      24kB
  [32m+ libgfortran5                             [0m        13.2.0  h582850c_5                conda-forge/linux-aarch64       1MB
  [32m+ libglib                                  [0m        2.78.4  h311d5f7_0                conda-forge/linux-aarch64       3MB
  [32m+ libgomp                                  [0m        13.2.0  hf8544c7_5                conda-forge/linux-aarch64     423kB
  [32m+ libiconv                                 [0m          1.17  h31becfc_2                conda-forge/linux-aarch64     706kB
  [32m+ libjpeg-turbo                            [0m         3.0.0  h31becfc_1                conda-forge/linux-aarch64     647kB
  [32m+ liblapack                                [0m         3.9.0  22_linuxaarch64_openblas  conda-forge/linux-aarch64      14kB
  [32m+ libnghttp2                               [0m        1.58.0  hb0e430d_1                conda-forge/linux-aarch64     678kB
  [32m+ libopenblas                              [0m        0.3.27  pthreads_h5a5ec62_0       conda-forge/linux-aarch64       4MB
  [32m+ libpng                                   [0m        1.6.43  h194ca79_0                conda-forge/linux-aarch64     294kB
  [32m+ libsanitizer                             [0m        13.2.0  h9a76618_5                conda-forge/linux-aarch64       4MB
  [32m+ libssh2                                  [0m        1.11.0  h492db2e_0                conda-forge/linux-aarch64     284kB
  [32m+ libstdcxx-devel_linux-aarch64            [0m        13.2.0  h0a96a4f_105              conda-forge/noarch             11MB
  [32m+ libstdcxx-ng                             [0m        13.2.0  h9a76618_5                conda-forge/linux-aarch64       4MB
  [32m+ libtiff                                  [0m         4.6.0  hf980d43_3                conda-forge/linux-aarch64     317kB
  [32m+ libuuid                                  [0m        2.38.1  hb4cce97_0                conda-forge/linux-aarch64      36kB
  [32m+ libwebp-base                             [0m         1.4.0  h31becfc_0                conda-forge/linux-aarch64     364kB
  [32m+ libxcb                                   [0m          1.15  h2a766a3_0                conda-forge/linux-aarch64     389kB
  [32m+ libzlib                                  [0m        1.2.13  h31becfc_5                conda-forge/linux-aarch64      67kB
  [32m+ make                                     [0m           4.3  h309ac5b_1                conda-forge/linux-aarch64     497kB
  [32m+ ncurses                                  [0m  6.4.20240210  h0425590_0                conda-forge/linux-aarch64     927kB
  [32m+ openssl                                  [0m         3.2.1  h31becfc_1                conda-forge/linux-aarch64       3MB
  [32m+ pango                                    [0m        1.52.1  h11ef544_0                conda-forge/linux-aarch64     457kB
  [32m+ pcre2                                    [0m         10.42  hd0f9c67_0                conda-forge/linux-aarch64     945kB
  [32m+ pixman                                   [0m        0.43.4  h2f0025b_0                conda-forge/linux-aarch64     295kB
  [32m+ pthread-stubs                            [0m           0.4  hb9de7d4_1001             conda-forge/linux-aarch64       6kB
  [32m+ r-base                                   [0m         4.3.3  h7dc8e12_0                conda-forge/linux-aarch64      26MB
  [32m+ readline                                 [0m           8.2  h8fc344f_1                conda-forge/linux-aarch64     294kB
  [32m+ sed                                      [0m           4.8  ha0d5d3d_0                conda-forge/linux-aarch64     289kB
  [32m+ sysroot_linux-aarch64                    [0m          2.17  h5b4a56d_14               conda-forge/noarch             16MB
  [32m+ tk                                       [0m        8.6.13  h194ca79_0                conda-forge/linux-aarch64       3MB
  [32m+ tktable                                  [0m          2.10  h4f9ca69_5                conda-forge/linux-aarch64      92kB
  [32m+ xorg-kbproto                             [0m         1.0.7  h3557bc0_1002             conda-forge/linux-aarch64      27kB
  [32m+ xorg-libice                              [0m         1.1.1  h7935292_0                conda-forge/linux-aarch64      60kB
  [32m+ xorg-libsm                               [0m         1.2.4  h5a01bc2_0                conda-forge/linux-aarch64      29kB
  [32m+ xorg-libx11                              [0m         1.8.9  h055a233_0                conda-forge/linux-aarch64     852kB
  [32m+ xorg-libxau                              [0m        1.0.11  h31becfc_0                conda-forge/linux-aarch64      15kB
  [32m+ xorg-libxdmcp                            [0m         1.1.3  h3557bc0_0                conda-forge/linux-aarch64      20kB
  [32m+ xorg-libxext                             [0m         1.3.4  h2a766a3_2                conda-forge/linux-aarch64      51kB
  [32m+ xorg-libxrender                          [0m        0.9.11  h7935292_0                conda-forge/linux-aarch64      37kB
  [32m+ xorg-libxt                               [0m         1.3.0  h7935292_1                conda-forge/linux-aarch64     384kB
  [32m+ xorg-renderproto                         [0m        0.11.1  h3557bc0_1002             conda-forge/linux-aarch64      10kB
  [32m+ xorg-xextproto                           [0m         7.3.0  h2a766a3_1003             conda-forge/linux-aarch64      30kB
  [32m+ xorg-xproto                              [0m        7.0.31  h3557bc0_1007             conda-forge/linux-aarch64      75kB
  [32m+ xz                                       [0m         5.2.6  h9cdd2b7_0                conda-forge/linux-aarch64     441kB
  [32m+ zlib                                     [0m        1.2.13  h31becfc_5                conda-forge/linux-aarch64      96kB
  [32m+ zstd                                     [0m         1.5.5  h4c53e97_0                conda-forge/linux-aarch64     529kB
```

### Environment info

```shell
Full logs of a failing build at https://circleci.com/api/v1.1/project/github/bioconda/bioconda-recipes/185015/output/107/0?file=true&allocation-id=662639e7003606346864521e-0-build%2FABCDEFGH
```

### PR DESCRIPTION
**Pull request by martin-g**
conda-build later copies it at
https://github.com/conda/conda-build/blob/e235104aca7c6bc0039a10f5ba2f2889c214c24d/conda_build/build.py#L821 as is.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
Is there a way to download the built artifact ?
The UI says `0 artifacts`, so I guess it is not uploaded.

Screenshot from 2024-04-30 15-18-11


From the debug logs for:
```
for folder in "./" "${PREFIX}" "${RECIPE_ROOT}" "${SRC_DIR}"; do
    for file in $(find ${folder} -name "LICENCE.txt"); do
        ls -la ${file}
        chmod +r ${file}
        ls -la ${file}
    done
done
```
```
+ for folder in '"./"' '"${PREFIX}"' '"${RECIPE_ROOT}"' '"${SRC_DIR}"'
2024-04-30T12:12:00.6154258Z ++ find ./ -name LICENCE.txt
2024-04-30T12:12:00.6161859Z + for file in '$(find ${folder} -name "LICENCE.txt")'
2024-04-30T12:12:00.6162730Z + ls -la ./LICENCE.txt
2024-04-30T12:12:00.6189609Z -rw------- 1 conda conda 4673 Oct  8  2010 ./LICENCE.txt
2024-04-30T12:12:00.6190206Z + chmod +r ./LICENCE.txt
2024-04-30T12:12:00.6200762Z + ls -la ./LICENCE.txt
2024-04-30T12:12:00.6226623Z -rw-r--r-- 1 conda conda 4673 Oct  8  2010 ./LICENCE.txt
2024-04-30T12:12:00.6232021Z + for folder in '"./"' '"${PREFIX}"' '"${RECIPE_ROOT}"' '"${SRC_DIR}"'
2024-04-30T12:12:00.6233148Z ++ find /home/conda/feedstock_root/build_artifacts/font-ttf-ubuntu_1714479024850/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place -name LICENCE.txt
2024-04-30T12:12:00.6249543Z + for folder in '"./"' '"${PREFIX}"' '"${RECIPE_ROOT}"' '"${SRC_DIR}"'
2024-04-30T12:12:00.6254331Z ++ find -name LICENCE.txt
2024-04-30T12:12:00.6278480Z + for file in '$(find ${folder} -name "LICENCE.txt")'
2024-04-30T12:12:00.6279087Z + ls -la ./LICENCE.txt
2024-04-30T12:12:00.6302733Z -rw-r--r-- 1 conda conda 4673 Oct  8  2010 ./LICENCE.txt
2024-04-30T12:12:00.6303279Z + chmod +r ./LICENCE.txt
2024-04-30T12:12:00.6314928Z + ls -la ./LICENCE.txt
2024-04-30T12:12:00.6339516Z -rw-r--r-- 1 conda conda 4673 Oct  8  2010 ./LICENCE.txt
2024-04-30T12:12:00.6340604Z + for folder in '"./"' '"${PREFIX}"' '"${RECIPE_ROOT}"' '"${SRC_DIR}"'
2024-04-30T12:12:00.6346013Z ++ find /home/conda/feedstock_root/build_artifacts/font-ttf-ubuntu_1714479024850/work -name LICENCE.txt
2024-04-30T12:12:00.6368831Z + for file in '$(find ${folder} -name "LICENCE.txt")'
2024-04-30T12:12:00.6369591Z + ls -la /home/conda/feedstock_root/build_artifacts/font-ttf-ubuntu_1714479024850/work/LICENCE.txt
2024-04-30T12:12:00.6392727Z -rw-r--r-- 1 conda conda 4673 Oct  8  2010 $SRC_DIR/LICENCE.txt
2024-04-30T12:12:00.6393717Z + chmod +r /home/conda/feedstock_root/build_artifacts/font-ttf-ubuntu_1714479024850/work/LICENCE.txt
2024-04-30T12:12:00.6404931Z + ls -la /home/conda/feedstock_root/build_artifacts/font-ttf-ubuntu_1714479024850/work/LICENCE.txt
2024-04-30T12:12:00.6428190Z -rw-r--r-- 1 conda conda 4673 Oct  8  2010 $SRC_DIR/LICENCE.txt
```
 I think I can simplify it to `chmod +r ${SRC_DIR}/LICENCE.txt`

**Comment by martin-g** [comment]
Hopefully this should fix the issue!
But I am not able to check the produced .conda archive to verify!

**Comment by xhochy** [comment]
You could upload the built artefacts using `store_build_artifacts`, see https://conda-forge.org/docs/maintainer/conda_forge_yml/#azure

**Comment by martin-g** [comment]
I was able to verify locally with `build-locally.py`:
```
font-ttf-ubuntu-feedstock on  read-perms-for-licence.txt via 🐍 v2.7.18 took 28s 
❯ cd build_artifacts/noarch/

font-ttf-ubuntu-feedstock/build_artifacts/noarch on  read-perms-for-licence.txt 
❯ ll
.rw-r--r-- martin martin 527 B  Tue Apr 30 15:38:55 2024  current_repodata.json
.rw-r--r-- martin martin 383 B  Tue Apr 30 15:38:55 2024  current_repodata.json.bz2
.rw-r--r-- martin martin 1.5 MB Tue Apr 30 15:38:55 2024  font-ttf-ubuntu-0.83-h77eed37_2.conda
.rw-r--r-- martin martin 2.6 KB Tue Apr 30 15:39:14 2024  index.html
.rw-r--r-- martin martin 505 B  Tue Apr 30 15:38:55 2024  repodata.json
.rw-r--r-- martin martin 364 B  Tue Apr 30 15:38:55 2024  repodata.json.bz2
.rw-r--r-- martin martin 505 B  Tue Apr 30 15:38:55 2024  repodata_from_packages.json
.rw-r--r-- martin martin 364 B  Tue Apr 30 15:38:55 2024  repodata_from_packages.json.bz2

font-ttf-ubuntu-feedstock/build_artifacts/noarch on  read-perms-for-licence.txt 
❯ unzip font-ttf-ubuntu-0.83-h77eed37_2.conda 
Archive:  font-ttf-ubuntu-0.83-h77eed37_2.conda
 extracting: metadata.json           
 extracting: pkg-font-ttf-ubuntu-0.83-h77eed37_2.tar.zst  
 extracting: info-font-ttf-ubuntu-0.83-h77eed37_2.tar.zst  

font-ttf-ubuntu-feedstock/build_artifacts/noarch on  read-perms-for-licence.txt 
❯ tar tvf pkg-font-ttf-ubuntu-0.83-h77eed37_2.tar.zst 
-rw-rw-r-- 0/0          205748 2024-04-30 15:38 fonts/UbuntuMono-R.ttf
-rw-rw-r-- 0/0          409608 2024-04-30 15:38 fonts/Ubuntu-LI.ttf
-rw-rw-r-- 0/0          350444 2024-04-30 15:38 fonts/Ubuntu-C.ttf
-rw-rw-r-- 0/0          333612 2024-04-30 15:38 fonts/Ubuntu-B.ttf
-rw-rw-r-- 0/0          353824 2024-04-30 15:38 fonts/Ubuntu-R.ttf
-rw-rw-r-- 0/0          216208 2024-04-30 15:38 fonts/UbuntuMono-BI.ttf
-rw-rw-r-- 0/0          366992 2024-04-30 15:38 fonts/Ubuntu-MI.ttf
-rw-rw-r-- 0/0          240020 2024-04-30 15:38 fonts/Ubuntu-Th.ttf
-rw-rw-r-- 0/0          386440 2024-04-30 15:38 fonts/Ubuntu-RI.ttf
-rw-rw-r-- 0/0          191400 2024-04-30 15:38 fonts/UbuntuMono-B.ttf
-rw-rw-r-- 0/0          210216 2024-04-30 15:38 fonts/UbuntuMono-RI.ttf
-rw-rw-r-- 0/0          341324 2024-04-30 15:38 fonts/Ubuntu-M.ttf
-rw-rw-r-- 0/0          356980 2024-04-30 15:38 fonts/Ubuntu-BI.ttf
-rw-rw-r-- 0/0          415552 2024-04-30 15:38 fonts/Ubuntu-L.ttf
-rw-r--r-- 0/0            4673 2010-10-08 05:08 info/licenses/LICENCE.txt
```

**Comment by dbast** [comment]
thanks!

**Comment by marcodelapierre** [comment]
This is great, it should unlock quite a few ARM-support PRs our team at Seqera is working on!

Thank you!

**Pull request merged**
